import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, CreditCard, LoaderCircle, ShieldCheck, Sparkles } from 'lucide-react';
import { getRemoteUser, listRemoteBuildRequests, startPesapalPayment, supabase } from '../lib/backend';

const PLAN_PRICES={starter:79,business:149,pro:299};
const MONTHLY_PRICES={starter:19,business:29,pro:49};
export default function BuildPayment(){
  const {id}=useParams(); const [request,setRequest]=useState(null); const [loading,setLoading]=useState(true); const [payType,setPayType]=useState('one-time'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{(async()=>{try{const u=await getRemoteUser();if(!u)throw new Error('Please sign in first.');const rows=await listRemoteBuildRequests(u.id);setRequest(rows.find(r=>r.id===id)||null);}catch(e){setError(e.message||'Could not load your build request.');}finally{setLoading(false);}})();},[id]);
  const plan=String(request?.plan||'business').toLowerCase(); const price=useMemo(()=>payType==='monthly'?MONTHLY_PRICES[plan]??29:PLAN_PRICES[plan]??149,[plan,payType]);
  async function pay(){setBusy(true);setError('');try{if(!request)throw new Error('Build request not found.');const result=await startPesapalPayment('build_request',request.id, payType);window.location.href=result.link;}catch(e){setError(e.message||'Could not start payment.');setBusy(false);}}
  if(loading)return <section className="container page-section narrow"><div className="success-card"><div className="success-icon"><LoaderCircle className="spin"/></div><h1>Loading your build…</h1></div></section>;
  if(error||!request)return <section className="container page-section narrow"><div className="success-card"><div className="success-icon"><ShieldCheck/></div><h1>We couldn't load this build.</h1><p>{error||'The build request could not be found.'}</p><Link className="secondary-button" to="/dashboard">Open dashboard</Link></div></section>;
  return <section className="container page-section narrow"><Link className="back-link" to="/start"><ArrowLeft size={15}/> Back to BOSS</Link><div className="page-heading simple"><div><div className="eyebrow"><Sparkles size={14}/> BOSS build</div><h1>Choose how you want to launch.</h1><p>Your request is ready. Payment moves it into the BOSS production queue.</p></div></div><div className="order-layout"><div className="form-card"><h3>Payment</h3><div className="payment-options"><label className={payType==='one-time'?'payment-option selected':'payment-option'}><input type="radio" checked={payType==='one-time'} onChange={()=>setPayType('one-time')}/><span><strong>Pay once — ${PLAN_PRICES[plan]??149}</strong><small>One-time build and delivery.</small></span></label><label className={payType==='monthly'?'payment-option selected':'payment-option'}><input type="radio" checked={payType==='monthly'} onChange={()=>setPayType('monthly')}/><span><strong>Subscribe — ${MONTHLY_PRICES[plan]??29}/month</strong><small>Pesapal can offer recurring card authorization during checkout when enabled.</small></span></label></div><button className="primary-button large full" onClick={pay} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<CreditCard size={17}/>} {busy?'Opening Pesapal…':`Pay ${price.toLocaleString()} UGX`}</button>{error&&<p className="error-text">{error}</p>}<div className="small-note"><ShieldCheck size={15}/> Your payment is processed by Pesapal. BOSS does not store card details.</div></div><aside className="summary-card"><div className="eyebrow">Your build</div><h3>{request.business_name}</h3><p>{request.plan?.toUpperCase()} package · {request.email}</p><div className="check-list"><div><CheckCircle2 size={14}/>Website: {request.recommended_website_name||'Custom'}</div>{request.recommended_bot_name&&<div><CheckCircle2 size={14}/>Assistant: {request.recommended_bot_name}</div>}<div><CheckCircle2 size={14}/>About 10 minutes after payment</div></div></aside></div></section>;
}
