import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, Bot, Clock3, ExternalLink, Globe2, LayoutTemplate, PackageCheck, Settings2, Sparkles } from 'lucide-react';
import { allProducts } from '../data/products';
import { getOrders, getProjects, getUser } from '../lib/store';
import { backendMode, getRemoteUser, listRemoteOrders, listRemoteProjects, listRemoteBuildRequests } from '../lib/backend';

export default function Dashboard() {
  const navigate = useNavigate(); const user = getUser();
  const [orders,setOrders]=useState(getOrders()); const [projects,setProjects]=useState(getProjects()); const [buildRequests,setBuildRequests]=useState([]);
  useEffect(()=>{(async()=>{ if(backendMode!=='supabase') return; const remote=await getRemoteUser(); if(!remote){navigate('/login');return;} const [o,p,b]=await Promise.all([listRemoteOrders(remote.id),listRemoteProjects(remote.id),listRemoteBuildRequests(remote.id)]); setOrders(o.map(x=>({id:x.id,userEmail:x.email,productId:x.product_id,productName:allProducts.find(a=>a.id===x.product_id)?.name||x.product_id,productType:allProducts.find(a=>a.id===x.product_id)?.type||'website',business:x.business,status:x.status,paymentStatus:x.payment_status,price:x.price,billingType:x.billing_type || 'one-time',createdAt:x.created_at,deliveryUrl:x.delivery_url||'',deliveryMessage:x.delivery_message||''}))); setProjects(p.map(x=>({id:x.id,productId:x.product_id,productName:x.product_name,type:x.type,live:x.live,data:x.data,updatedAt:x.updated_at}))); setBuildRequests(b.map(x=>({id:x.id,business:x.business_name,status:x.status,plan:x.plan,price:x.price,paymentStatus:x.payment_status||'Awaiting payment',billingType:x.billing_type||'one-time',createdAt:x.created_at,deliveryUrl:x.delivery_url||'',deliveryMessage:x.delivery_message||'',adminMessage:x.admin_message||''})));  })().catch(()=>{});},[navigate]);
  const active = projects.filter(p => p.live);
  return <section className="container page-section">
    <div className="page-heading"><div><div className="eyebrow"><Sparkles size={14}/> Customer area</div><h1>Welcome back{user?.name ? `, ${user.name}` : ''}.</h1><p>Manage orders, websites and chatbots from one place.</p></div><Link className="primary-button" to="/order">Start a new order <ArrowRight size={16}/></Link></div>
    <div className="stats-grid"><div><PackageCheck/><span>Orders</span><strong>{orders.length}</strong></div><div><Clock3/><span>In progress</span><strong>{orders.filter(o => o.status !== 'Completed').length}</strong></div><div><Globe2/><span>Published</span><strong>{active.length}</strong></div><div><Bot/><span>Chatbots</span><strong>{projects.filter(p => p.type==='chatbot').length}</strong></div></div>
    {buildRequests.length > 0 && <div className="table-card" style={{marginBottom:'1.5rem'}}><div className="table-head"><h3>My BOSS build requests</h3><span>{buildRequests.length}</span></div><div className="order-list">{buildRequests.map(r=><div className="order-row" key={r.id}><div className="order-icon"><Sparkles/></div><div className="order-main"><strong>{r.business || 'Business setup'}</strong><span>{r.plan || 'Custom'} · {new Date(r.createdAt).toLocaleDateString()}</span>{r.adminMessage && <small>{r.adminMessage}</small>}{r.deliveryMessage && <small>{r.deliveryMessage}</small>}{r.deliveryUrl && <a className="text-link" href={r.deliveryUrl} target="_blank" rel="noreferrer">Open your delivered build <ExternalLink size={12}/></a>}{r.paymentStatus !== 'Paid' && <Link className="small-button" to={`/build-payment/${r.id}`}>Pay with Pesapal <ArrowRight size={13}/></Link>}</div><span className={`status status-${String(r.status).toLowerCase().replace(/\s+/g,'-')}`}>{r.status}</span></div>)}</div></div>}
    <div className="dashboard-grid">
      <div className="table-card"><div className="table-head"><h3>My projects</h3><Link className="text-link" to="/websites">Browse more</Link></div>{projects.length ? <div className="project-list">{projects.map(p => <div className="project-tile" key={p.id}><div className="order-icon">{p.type==='website'?<LayoutTemplate/>:<Bot/>}</div><div><strong>{p.productName}</strong><span>{p.live?'Published':'Draft'} · updated {new Date(p.updatedAt || Date.now()).toLocaleDateString()}</span></div><div className="project-tile-actions"><Link className="small-button" to={`/builder/${p.type}/${p.productId}`}><Settings2 size={14}/> Edit</Link>{p.live && <Link className="small-button" to={`/published/${encodeURIComponent(p.id)}`}><ExternalLink size={14}/> Open</Link>}</div></div>)}</div> : <div className="empty-state"><h3>Nothing built yet.</h3><p>Choose a ready-made website or chatbot and customize it in BOSS Studio.</p><div className="hero-actions centered"><Link className="primary-button" to="/websites">Websites</Link><Link className="secondary-button" to="/chatbots">Chatbots</Link></div></div>}</div>
      <div className="table-card"><div className="table-head"><h3>Recent orders</h3><span>{orders.length ? `${orders.length} total` : 'No orders yet'}</span></div>{orders.length ? <div className="order-list">{orders.slice(0,6).map(o => <div className="order-row" key={o.id}><div className="order-icon">{o.productType === 'website' ? <LayoutTemplate/> : <Bot/>}</div><div className="order-main"><strong>{o.productName}</strong><span>{o.business || 'Business'} · {new Date(o.createdAt).toLocaleDateString()}</span>{o.deliveryMessage && <small>{o.deliveryMessage}</small>}{o.deliveryUrl && <a className="text-link" href={o.deliveryUrl} target="_blank" rel="noreferrer">Open your delivered build <ExternalLink size={12}/></a>}</div><span className={`status status-${String(o.status).toLowerCase().replace(/\s+/g,'-')}`}>{o.status}</span><span className="payment">{o.paymentStatus}</span></div>)}</div> : <div className="empty-state small-empty">Place your first order to see it here.</div>}</div>
    </div>
  </section>;
}
