import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Calendar, MapPin, MessageCircle, ShoppingBag } from 'lucide-react';
import { websites } from '../data/products';

export default function DemoWebsite() {
  const { id } = useParams();
  const site = websites.find(s => s.id === id) || websites[0];
  if (site.id === 'restaurant-pro') return <RestaurantDemo site={site}/>;
  if (site.id === 'store-pro') return <StoreDemo site={site}/>;
  if (site.id === 'portfolio-pro') return <PortfolioDemo site={site}/>;
  return <BusinessDemo site={site}/>;
}

function DemoShell({ site, children }) { return <div className="demo-page"><div className="demo-ribbon"><span>LIVE TEMPLATE DEMO</span><Link to={`/product/${site.type}/${site.id}`}>Get this template <ArrowRight size={14}/></Link></div>{children}</div>; }
function RestaurantDemo({ site }) { return <DemoShell site={site}><div className="demo-restaurant"><nav><strong>EMBER & SPOON</strong><div><a href="#menu">Menu</a><a href="#story">Story</a><a href="#visit">Visit</a><Link className="demo-button" to="/order" state={{product:site}}>Book a table</Link></div></nav><header><div className="demo-hero-copy"><span className="kicker">Modern dining · Kampala</span><h1>Good food. Warm room. Zero fuss.</h1><p>Seasonal plates, bold drinks and a place to stay awhile.</p><div className="demo-actions"><a className="demo-button" href="#menu">See the menu</a><a className="ghost-demo" href="#visit">Find us</a></div></div><div className="demo-hero-art"><div className="plate">EMBER</div></div></header><section id="menu" className="demo-section"><span className="kicker">Tonight's highlights</span><h2>A menu built for sharing.</h2><div className="menu-cards"><div><span>01</span><strong>Charred chicken</strong><em>Rosemary · lemon · herbs</em><b>$14</b></div><div><span>02</span><strong>Spiced prawns</strong><em>Garlic · chilli · lime</em><b>$16</b></div><div><span>03</span><strong>Chocolate tart</strong><em>Salt · cocoa · cream</em><b>$8</b></div></div></section><section id="visit" className="visit-bar"><div><MapPin/> Plot 24, Kololo</div><div><Calendar/> Tue–Sun · 12pm–11pm</div><div><MessageCircle/> WhatsApp us</div></section></div></DemoShell>; }
function BusinessDemo({ site }) { return <DemoShell site={site}><div className="business-demo"><nav><strong>Northstar</strong><div><a href="#services">Services</a><a href="#proof">Results</a><a href="#contact">Contact</a><Link className="demo-button dark" to="/order" state={{product:site}}>Start a project</Link></div></nav><section className="business-hero"><div><span className="kicker">Strategy · Design · Growth</span><h1>Make your next business move your best one.</h1><p>Northstar helps ambitious teams build a sharper brand, website and customer journey.</p><Link className="demo-button dark" to="/order" state={{product:site}}>Talk to us <ArrowRight size={15}/></Link></div><div className="metric-card"><strong>+42%</strong><span>Lead growth after launch</span><div className="bars"><i/><i/><i/><i/><i/></div></div></section><section id="services" className="business-services"><div><span className="kicker">What we do</span><h2>Clear work. Measurable outcomes.</h2></div><div className="service-grid"><article><b>01</b><h3>Brand systems</h3><p>Identity, positioning and messaging.</p></article><article><b>02</b><h3>Web experiences</h3><p>Websites built to convert attention into action.</p></article><article><b>03</b><h3>Growth ops</h3><p>Funnels, analytics and content systems.</p></article></div></section><section id="contact" className="business-cta"><h2>Ready to move?</h2><Link className="demo-button dark" to="/order" state={{product:site}}>Get started <ArrowRight size={15}/></Link></section></div></DemoShell>; }
function StoreDemo({ site }) { return <DemoShell site={site}><div className="store-demo"><nav><strong>FORME</strong><div><a href="#new">New in</a><a href="#shop">Shop</a><a href="#about">About</a><Link className="demo-button" to="/order" state={{product:site}}><ShoppingBag size={15}/> Order site</Link></div></nav><section className="store-hero"><div><span className="kicker">New collection · 2026</span><h1>Objects made to keep.</h1><p>Simple, useful pieces for everyday spaces.</p><a className="demo-button" href="#shop">Shop collection</a></div><div className="product-orb"><div/></div></section><section id="shop" className="store-products"><article><div className="shape one"/><span>01 · HOME</span><h3>Arc lamp</h3><b>$48</b></article><article><div className="shape two"/><span>02 · DESK</span><h3>Fold tray</h3><b>$26</b></article><article><div className="shape three"/><span>03 · TEXTILE</span><h3>Linen throw</h3><b>$62</b></article></section></div></DemoShell>; }
function PortfolioDemo({ site }) { return <DemoShell site={site}><div className="portfolio-demo"><nav><strong>AMANI K.</strong><div><a href="#work">Work</a><a href="#about">About</a><Link className="demo-button" to="/order" state={{product:site}}>Hire me</Link></div></nav><section className="portfolio-hero"><span className="kicker">Designer · Photographer · Creative</span><h1>I make brands look impossible to ignore.</h1><p>Selected work across identity, campaigns and digital experiences.</p></section><section id="work" className="work-grid"><div className="work-card tall">01</div><div className="work-card">02</div><div className="work-card">03</div><div className="work-card wide">04</div></section><section id="about" className="portfolio-about"><div><span className="kicker">About</span><h2>Good work starts with a clear idea.</h2></div><p>From the first sketch to the final launch, this portfolio template gives creators a focused, professional home online.</p></section></div></DemoShell>; }
