import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Bot, CheckCircle2, Download, MessageCircle, Phone, ShoppingBag } from 'lucide-react';
import { getProject } from '../lib/store';
import { allProducts } from '../data/products';
import { backendMode, getRemoteProject, saveRemoteMessage } from '../lib/backend';
import { downloadText, websiteHtml } from '../lib/export';

export default function Published() {
  const { id } = useParams(); const decoded=decodeURIComponent(id); const [project,setProject]=useState(getProject(decoded)); const [message,setMessage]=useState(''); const [messages,setMessages]=useState([]); const [loading,setLoading]=useState(false);
  useEffect(()=>{if(backendMode==='supabase')getRemoteProject(decoded).then(async x=>{ if(x){ setProject({id:x.id,productId:x.product_id,productName:x.product_name,type:x.type,live:x.live,data:x.data}); return; } const r=await fetch(`/api/public-project?id=${encodeURIComponent(decoded)}`); if(r.ok){ const p=await r.json(); setProject({id:p.id,productId:p.product_id,productName:p.product_name,type:p.type,live:p.live,data:p.data}); }}).catch(()=>{});},[decoded]);
  if (!project) return <section className="container page-section"><h1>Project not found.</h1><Link className="primary-button" to="/dashboard">Dashboard</Link></section>;
  const product = allProducts.find(p => p.id === project.productId); const d = project.data || {};
  async function send() { const text=message.trim(); if(!text)return; setMessages(prev=>[...prev,{role:'user',text}]); setMessage(''); setLoading(true); try { if(backendMode==='supabase'){ const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId:project.id,message:text})}); const data=await r.json(); const answer=data.reply || 'I am not sure yet.'; setMessages(prev=>[...prev,{role:'bot',text:answer}]); await saveRemoteMessage({projectId:project.id,sender:'user',message:text}).catch(()=>{}); await saveRemoteMessage({projectId:project.id,sender:'bot',message:answer}).catch(()=>{}); } else { const lower=text.toLowerCase(); const match=(d.faqs||[]).find(f=>lower.includes(String(f.q||'').toLowerCase().split(' ').slice(0,3).join(' ')) || String(f.q||'').toLowerCase().includes(lower)); const answer=match?.a || 'I can help with the information in this assistant. Try asking about our services, hours, prices or contact details.'; setMessages(prev=>[...prev,{role:'bot',text:answer}]); } } finally { setLoading(false); } }
  if (project.type === 'chatbot') {
    return <section className="published-page"><div className="published-toolbar"><strong>BOSS</strong><span><CheckCircle2 size={14}/> Published bot</span><button className="small-button" onClick={()=>downloadText(`${d.botName||'boss-chatbot'}.json`,JSON.stringify(project,null,2),'application/json')}><Download size={14}/> Export</button><Link to="/dashboard">Manage</Link></div><div className="published-bot-wrap"><div className="bot-window"><div className="chat-header"><div className="bot-avatar"><Bot size={18}/></div><div><strong>{d.botName}</strong><span>{loading?'Thinking…':`Online · ${d.tone}`}</span></div></div><div className="bot-messages"><div className="chat-msg bot">{d.welcome}</div>{messages.map((m,i)=><div key={i} className={`chat-msg ${m.role}`}>{m.text}</div>)}{!messages.length && (d.faqs||[]).slice(0,2).map((faq,i)=><button className="quick-row" key={i} onClick={()=>{setMessages(prev=>[...prev,{role:'user',text:faq.q},{role:'bot',text:faq.a}])}}>{faq.q}</button>)}</div><div className="chat-compose"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask a question..."/><button onClick={send} disabled={loading}><MessageCircle size={15}/></button></div></div></div></section>;
  }
  return <section className="published-site" style={{'--accent':d.primary}}><div className="published-toolbar"><strong>{d.business}</strong><span><CheckCircle2 size={14}/> Published website</span><button className="small-button" onClick={()=>downloadText(`${d.business||'boss-site'}.html`,websiteHtml(project),'text/html')}><Download size={14}/> Export HTML</button><Link to="/dashboard">Manage</Link></div><header><strong>{d.business}</strong><nav><span>Home</span><span>Services</span><span>About</span><span>Contact</span></nav><a href={`https://wa.me/${String(d.whatsapp || '').replace(/\D/g,'')}`}>WhatsApp</a></header><main><div className="pub-kicker">BOSS WEBSITE • {product?.category || 'Business'}</div><h1>{d.tagline}</h1><p>{d.location} · {d.phone}</p><div className="pub-actions"><button><Phone size={15}/>{d.cta}</button><a href={`https://wa.me/${String(d.whatsapp || '').replace(/\D/g,'')}`}><MessageCircle size={15}/> WhatsApp</a></div></main><div className="pub-sections">{(d.sections||[]).map(x=><article key={x}><ShoppingBag size={18}/><h3>{x}</h3><p>Ready for your business content, offers and customer information.</p></article>)}</div><footer>Published with BOSS · Manage this site from your dashboard.</footer></section>;
}
