import { useEffect } from 'react';
import { Routes, Route } from 'react-router-dom';
import Header from './components/Header'; import Footer from './components/Footer';
import Home from './pages/Home'; import Websites from './pages/Websites'; import Chatbots from './pages/Chatbots'; import Product from './pages/Product'; import Order from './pages/Order'; import Dashboard from './pages/Dashboard'; import Admin from './pages/Admin'; import Login from './pages/Login'; import DemoWebsite from './pages/DemoWebsite'; import DemoChatbot from './pages/DemoChatbot'; import Builder from './pages/Builder'; import Published from './pages/Published'; import NotFound from './pages/NotFound';
import PaymentReturn from './pages/PaymentReturn';
import BuildPayment from './pages/BuildPayment';
import SetupWizard from './pages/SetupWizard';
import { backendMode, subscribeToAuth, getRemoteUser, getRemoteProfile, toLocalUser } from './lib/backend';
import { clearUser, setUser } from './lib/store';
export default function App(){
  useEffect(()=>{ if(backendMode!=='supabase') return; let mounted=true; getRemoteUser().then(async u=>{ if(!mounted)return; if(!u){clearUser();return;} const profile=await getRemoteProfile(u.id).catch(()=>null); setUser(toLocalUser(u,profile)); }).catch(()=>{}); const sub=subscribeToAuth(async (_event,session)=>{ window.dispatchEvent(new CustomEvent('boss-password-recovery',{detail:{event:_event}})); if(!session?.user){clearUser();window.dispatchEvent(new Event('boss-auth-changed'));return;} const profile=await getRemoteProfile(session.user.id).catch(()=>null); setUser(toLocalUser(session.user,profile)); window.dispatchEvent(new Event('boss-auth-changed')); }); return ()=>{mounted=false; sub?.subscription?.unsubscribe?.();}; },[]);
  return <div className="app-shell"><Header/><main className="page-wrap"><Routes><Route path="/" element={<Home/>}/><Route path="/websites" element={<Websites/>}/><Route path="/chatbots" element={<Chatbots/>}/><Route path="/product/:type/:id" element={<Product/>}/><Route path="/order" element={<Order/>}/><Route path="/start" element={<SetupWizard/>}/><Route path="/payment/return" element={<PaymentReturn/>}/><Route path="/build-payment/:id" element={<BuildPayment/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/admin" element={<Admin/>}/><Route path="/login" element={<Login/>}/><Route path="/builder/:type/:id" element={<Builder/>}/><Route path="/published/:id" element={<Published/>}/><Route path="/demo/site/:id" element={<DemoWebsite/>}/><Route path="/demo/bot/:id" element={<DemoChatbot/>}/><Route path="*" element={<NotFound/>}/></Routes></main><Footer/></div>}
